on: push
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    with:
      NOMAD_VAR_PORTS: '{ 80 = "http"}'
      NOMAD_VAR_CHECK_PROTOCOL: 'tcp'
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_SECRETS: '{ "GLTOK"="${{ secrets.GLTOK }}", "RSA"="${{ secrets.RSA }}" }'
